# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUCPFNlbsW_vSOYnhIxheSz5xqBrSS-j
"""

# Prediciones Visuales

import numpy as np

clases = ["T-shirt", "Trouser", "Pullover", "Dress", "Coat",
               "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

predictiones = model_cnn.predict(X_test_cnn)

plt.figure(figsize=(10,5))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(X_test[i], cmap='gray')
    pred_label = clases[np.argmax(predictions[i])]
    true_label = clases[y_test[i]]
    plt.title(f"P:{pred_label}\nT:{true_label}")
    plt.axis('off')

plt.tight_layout()
plt.savefig("predicciones.png", dpi=300)
plt.show()

# Matriz de con

from sklearn.metrics import confusion_matrix
import seaborn as sns

y_pred = np.argmax(predictiones, axis=1)

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Matriz de Confusión")

plt.savefig("confusion_matrix.png", dpi=300)
plt.show()

# Graficos

plt.figure()
plt.plot(history_cnn.history['accuracy'])
plt.plot(history_cnn.history['val_accuracy'])
plt.title("Accuracy")

plt.savefig("accuracy.png", dpi=300)
plt.show()